site_name: Beavers
site_url: https://beavers.readthedocs.io/en/latest/
repo_url: https://github.com/tradewelltech/beavers
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - header.autohide
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    scheme: slate
    accent: green
  logo: static/icons/beavers/logo.svg
  favicon: static/icons/beavers/icon.png

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false

markdown_extensions:
  - def_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets:
  - pymdownx.emoji
  - pymdownx.highlight
  - attr_list
  - md_in_html
extra:
  project_name: "beavers"


nav:
  - Home:
    - index.md
  - Concepts:
    - concepts/1_dag.md
    - concepts/2_advanced.md
    - concepts/3_replay.md
    - concepts/4_kafka.md
  - API Reference:
    - reference/engine.md
    - reference/kafka.md
    - reference/replay.md
  - install.md
  - development.md
