name: beavers CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
      fail-fast: false
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install pip
        run: "python -m pip install --upgrade pip"
      - name: Install tox and poetry
        run: "python -m pip install tox tox-gh-actions poetry==1.7.1"
      - name: Install poetry plugin
        run: 'poetry self add "poetry-dynamic-versioning[plugin]"'

      - name: Run tox
        run: tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: "matrix.python-version == '3.10'"
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
